add support for docker
icgc-argo-workflows/nextflow-data-processing-utility-tools pull request #49
Opened 2022-12-14 21:27 UTC by edsu7

2022-12-19 23:06 UTC, lindaxiang requested changes

2022-12-19 23:24 UTC, edsu7 commented on process/score_upload.nf
> +        containerOptions "-v \$(pwd):/song-client/logs"
Fixed in
https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/blob/1a01b2e4e0f1acbee0fa08d6016ab5702d8bf818/process/score_upload.nf#L37-L40

2023-01-04 14:22 UTC, lindaxiang commented on process/score_upload.nf
> +        containerOptions "-v \$(pwd):/score-client/logs"
A very minor suggestion, can we change to 
```
-v \$(pwd)/logs:/score-client/logs
```

2023-01-04 14:23 UTC, lindaxiang approved these changes
- A very minor suggestion. 
- Question: do we plan to make similar changes to `song-score-download`?

2023-01-05 19:40 UTC, edsu7 commented
closing. new branch in https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/51

2023-01-05 19:40 UTC, closed without merging